### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by revolter** [krzysztofzablocki/KZLinkedConsole#30]
It stopped working a couple of time ago and I don't know why. In `Alcatraz`, it shows up as installed, I never clicked "don't allow" on the Xcode's new plugin detected alert. How can I debug it?

**Comment by krzysztofzablocki** [comment]
Try reinstalling it as xcode has changed recently and the plugin might get outdated (it has to be changed each time xcode is updated because)

**Comment by revolter** [comment]
It worked, thanks.

**Comment by revolter** [comment]
It still doesn't work on the Mac at work, using OS X 10.10.5

**Comment by revolter** [comment]
@krzysztofzablocki, I get these errors in the Console.app:

```
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:30:33: error: expected initial value after '='
        let didChangeSelector = #selector(KZLinkedConsole.didChange(_:))
                                ^
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:30:32: error: consecutive statements on a line must be separated by ';'
        let didChangeSelector = #selector(KZLinkedConsole.didChange(_:))
                               ^
                               ;
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:30:33: error: expected expression
        let didChangeSelector = #selector(KZLinkedConsole.didChange(_:))
                                ^
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:57:48: error: expected initial value after '='
            let fixAttributesInRangeSelector = #selector(NSTextStorage.fixAttributesInRange(_:))
                                               ^
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:57:47: error: consecutive statements on a line must be separated by ';'
            let fixAttributesInRangeSelector = #selector(NSTextStorage.fixAttributesInRange(_:))
                                              ^
                                              ;
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:57:48: error: expected expression
            let fixAttributesInRangeSelector = #selector(NSTextStorage.fixAttributesInRange(_:))
                                               ^
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:58:51: error: expected initial value after '='
            let kz_fixAttributesInRangeSelector = #selector(NSTextStorage.kz_fixAttributesInRange(_:))
                                                  ^
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:58:50: error: consecutive statements on a line must be separated by ';'
            let kz_fixAttributesInRangeSelector = #selector(NSTextStorage.kz_fixAttributesInRange(_:))
                                                 ^
                                                 ;
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:58:51: error: expected expression
            let kz_fixAttributesInRangeSelector = #selector(NSTextStorage.kz_fixAttributesInRange(_:))
                                                  ^
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:60:37: error: expected initial value after '='
            let mouseDownSelector = #selector(NSTextView.mouseDown(_:))
                                    ^
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:60:36: error: consecutive statements on a line must be separated by ';'
            let mouseDownSelector = #selector(NSTextView.mouseDown(_:))
                                   ^
                                   ;
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:60:37: error: expected expression
            let mouseDownSelector = #selector(NSTextView.mouseDown(_:))
                                    ^
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:61:40: error: expected initial value after '='
            let kz_mouseDownSelector = #selector(NSTextView.kz_mouseDown(_:))
                                       ^
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:61:39: error: consecutive statements on a line must be separated by ';'
            let kz_mouseDownSelector = #selector(NSTextView.kz_mouseDown(_:))
                                      ^
                                      ;
/Users/Iulian/Library/Application Support/Alcatraz/Plug-ins/KZLinkedConsole/KZLinkedConsole/KZLinkedConsole.swift:61:40: error: expected expression
            let kz_mouseDownSelector = #selector(NSTextView.kz_mouseDown(_:))
```
